// Modules métiers pilotés par la donnée (Plan.modules) — référence : prompt maître §10.4.
export enum ModuleMetier {
  ACCUEIL_ADMISSION = 'ACCUEIL_ADMISSION',
  ADMINISTRATION_DIRECTION = 'ADMINISTRATION_DIRECTION',
  BLOC_OPERATOIRE = 'BLOC_OPERATOIRE',
  COMPTABILITE_FACTURATION = 'COMPTABILITE_FACTURATION',
  CONSULTATIONS_MEDICALES = 'CONSULTATIONS_MEDICALES',
  HOSPITALISATION = 'HOSPITALISATION',
  IMAGERIE_MEDICALE = 'IMAGERIE_MEDICALE',
  KINESITHERAPIE_READAPTATION = 'KINESITHERAPIE_READAPTATION',
  LABORATOIRE = 'LABORATOIRE',
  LOGISTIQUE_STOCK = 'LOGISTIQUE_STOCK',
  PHARMACIE = 'PHARMACIE',
  RH = 'RH',
  SECURITE_CONFORMITE = 'SECURITE_CONFORMITE',
  URGENCES = 'URGENCES',
  TABLEAU_DE_BORD_STATISTIQUES = 'TABLEAU_DE_BORD_STATISTIQUES',
}
