// Référence : docs/phase-0/cartographie-fonctionnelle.md §3 et matrice-rbac.md
export enum Role {
  // PLATFORM
  SUPER_ADMIN = 'SUPER_ADMIN',

  // ETABLISSEMENT — Direction/Système
  ADMIN_ETABLISSEMENT = 'ADMIN_ETABLISSEMENT',
  DIRECTEUR = 'DIRECTEUR',
  ADMIN_SYSTEME = 'ADMIN_SYSTEME',

  // ETABLISSEMENT — Médical
  MEDECIN = 'MEDECIN',
  CHIRURGIEN = 'CHIRURGIEN',
  INFIRMIER = 'INFIRMIER',
  ANESTHESISTE = 'ANESTHESISTE',
  SAGE_FEMME = 'SAGE_FEMME',
  PSYCHIATRE = 'PSYCHIATRE',
  KINESITHERAPEUTE = 'KINESITHERAPEUTE',
  DIETETICIEN = 'DIETETICIEN',

  // ETABLISSEMENT — Diagnostic
  RADIOLOGUE = 'RADIOLOGUE',
  MANIPULATEUR_RADIO = 'MANIPULATEUR_RADIO',
  LABORANTIN = 'LABORANTIN',
  BIOLOGISTE = 'BIOLOGISTE',

  // ETABLISSEMENT — Pharmacie/Logistique
  PHARMACIEN = 'PHARMACIEN',
  AGENT_STERILISATION = 'AGENT_STERILISATION',
  MAGASINIER = 'MAGASINIER',
  TECHNICIEN_MAINTENANCE = 'TECHNICIEN_MAINTENANCE',

  // ETABLISSEMENT — Administratif
  AGENT_ACCUEIL_ADMISSION = 'AGENT_ACCUEIL_ADMISSION',
  SECRETAIRE_MEDICALE = 'SECRETAIRE_MEDICALE',
  CAISSIER_FACTURATION = 'CAISSIER_FACTURATION',
  GESTIONNAIRE_LITS = 'GESTIONNAIRE_LITS',
  ASSISTANT_SOCIAL = 'ASSISTANT_SOCIAL',
  RH = 'RH',

  // PATIENT
  PATIENT = 'PATIENT',
}

export const PLATFORM_ROLES: ReadonlySet<Role> = new Set([Role.SUPER_ADMIN]);

export const PATIENT_ROLES: ReadonlySet<Role> = new Set([Role.PATIENT]);
